import { MouseEvent } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Button from "@/components/Button";

export default function Home() {
  function handleClick(event: MouseEvent<HTMLButtonElement>) {
    console.log("Botão Bem-vindo clicado", event);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.page}>
        <Button
          label="Bem-vindo"
          className={styles.welcomeButton}
          onClick={handleClick}
        />
      </div>
    </>
  );
}
